### ISSUE TITLE
Better Gas estimate flow and sanity checks

### ISSUE THREAD

**Issue by thecryptodrive** [notional-labs/multisig-ui#146]
![image](https://github.com/notional-labs/multisig-ui/assets/22358264/fecc5d2e-6147-4956-a92e-6d65ce33e54e)

I was able to create a tx without estimating gas and setting fee, the hyperlink to estimate gas is so small and grey it can be missed, it should be a mandatory part of the flow somehow, please suggest a better way that maybe grey's out the Create Transaction button until gas is estimated

**Comment by sontrinh16** [comment]
the estimate is just an optional
