### ISSUE TITLE
Receiving "Failed to fetch" when attempting to Create a Multi-Sig

### ISSUE THREAD

**Issue by ToggLeTek** [notional-labs/multisig-ui#20]
Hello! When attempting to create a multisig, the tool is erroring with "Failed to fetch."

![failed_to_fetch_gui](https://user-images.githubusercontent.com/102473214/180312726-e08900cd-1959-499e-9866-d05aaa3c99e5.png)

This is happening both on the website and a cloned local copy. It is not the particular end node, but I believe the method with which the data is being sent to the nodes:

![failed_to_fetch_cors](https://user-images.githubusercontent.com/102473214/180312725-97053945-319a-4922-a323-76b2597e5e7a.png)

It's looking like a CORS issue is present.

**Comment by sontrinh16** [comment]
Hi, thankyou for the report. I believe we have solve the problem by switching to api call insteal of rpc

**Comment by ToggLeTek** [comment]
This looks like it was resolved! Thank you again for the wonderful tool!
